services:
  - type: web
    name: tale-trail-api
    runtime: docker
    repo: https://github.com/bharambetr2002/TaleTrail-Backend
    branch: main
    plan: free
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
