services:
  - type: web
    name: taletrail-api
    env: dotnet
    buildCommand: |
      cd TaleTrail.API
      dotnet restore
      dotnet publish -c Release -o publish
    startCommand: |
      cd TaleTrail.API/publish
      dotnet TaleTrail.API.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:10000
    healthCheckPath: /health
