services:
  - type: web
    name: taletrail-api
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ENABLE_SWAGGER
        value: true
      - key: SUPABASE_URL
        sync: false # You'll set this manually in dashboard
      - key: SUPABASE_KEY
        sync: false # You'll set this manually in dashboard
      - key: ALLOWED_ORIGINS
        value: "*" # Change this to your actual frontend URLs
    buildCommand: ""
    startCommand: ""
    healthCheckPath: /health
